### ISSUE TITLE
Porting code to Soundpipe

### ISSUE THREAD

**Issue by PaulBatchelor** [martineastwood/mverb#1]
Hello,

I am the developer of an open source project called [Soundpipe](http://www.github.com/paulbatchelor/soundpipe). 

I would love to adopt your C++ code to fit a Soundpipe module (which will be rewritten in C99 C). 

Bearing in mind that my project is MIT licensed and not GPL licensed, would this be okay?

Many thanks,

-Paul

**Comment by martineastwood** [comment]
No problem, go for it.
